<Project>
  <Target Name="BuildSolutionProjectsSerially" BeforeTargets="Build">
    <MSBuild
      Projects="@(ProjectReference)"
      BuildInParallel="False"
      Properties="BuildInParallel=false;RestoreBuildInParallel=false" />
    <ItemGroup>
      <ProjectReference Remove="@(ProjectReference)" />
    </ItemGroup>
  </Target>
</Project>
