// <copyright file="ProjectionWriteConformanceIntegrationTests.cs" company="ITANEO">
// Copyright (c) ITANEO. All rights reserved.
// Licensed under the MIT License.
// </copyright>

// ATDD RED-PHASE SCAFFOLD — generated by /bmad-testarch-atdd 2026-05-19.
// Story: 10.4 (10-4-projection-write-conformance-and-recovery-tests).
// Risk: R-001 (silent last-writer-wins on projection:tenant-index:singleton) — score 9, BLOCK.
// Test design: _bmad-output/test-artifacts/test-design-epic-10.md.
// Tier: 2 (DAPR + Redis required; gates on `dapr init` availability).
//
// Sanity check that the scripted state-store fake in the Tier 1 conformance tests
// behaves identically to a real DAPR-backed Redis state store under ETag conflict.

using System;
using System.Net.Sockets;
using System.Threading.Tasks;

using Hexalith.Tenants.Server.Projections;

using Shouldly;

namespace Hexalith.Tenants.Server.Tests.Projections;

/// <summary>
/// Tier 2 integration test for R-001: real DAPR-backed conflict-then-success on the
/// singleton tenant-index key. Skipped when DAPR sidecar / Redis state store is not
/// available locally or in CI (matches the post-Epic-3 SCP-2026-05-12 R3-A4
/// precondition-gating pattern).
/// </summary>
public class ProjectionWriteConformanceIntegrationTests
{
    private const string DaprStateStoreHost = "127.0.0.1";
    private const int DaprStateStoreRedisPort = 6379;
    private const string SkipReason =
        "ATDD RED PHASE — Tier 2 integration test. Story 10.4 must:\n" +
        "  1. Skip-by-precondition when DAPR/Redis unavailable (call EnsureDaprAvailableOrSkip()).\n" +
        "  2. Use a real DaprClient + DaprTenantProjectionStateStore wrapper that forces an ETag\n" +
        "     mismatch on attempt 1 (e.g., interleaved writer or seeded conflicting state).\n" +
        "  3. Invoke TenantProjectionWritePolicy.SaveWithOptimisticConcurrencyAsync<TenantIndexReadModel>\n" +
        "     and assert the persisted state in Redis matches the Tier 1 conformance expectations.\n" +
        "  4. Tear down the test key from the real state store on completion (avoid leaking state).\n" +
        "Remove this Skip and implement once DAPR-backed test harness exists.";

    [Fact(Skip = SkipReason)]
    public async Task TenantIndex_RealDaprBackedConflictThenSuccess_PreservesIndexAsync()
    {
        EnsureDaprAvailableOrSkip();

        // ARRANGE — same conformance scenario as Tier 1 T-R001-UNIT-001 but against
        // real DAPR + Redis. Seed Redis with a pre-existing singleton index containing
        // tenant-A. Force an ETag mismatch on attempt 1 via an interleaved writer that
        // saves tenant-B to the same key between our read and our save.
        //
        // TODO(Story-10.4):
        //   - Construct a DaprClient via DaprClientBuilder using a known sidecar port.
        //   - Construct DaprTenantProjectionStateStore wrapping that client.
        //   - Seed the key with TenantIndexReadModel containing tenant-A.
        //   - Inject a write-side helper that performs a write to the same key between
        //     our read and our save (interleaved-writer pattern).
        //   - Invoke TenantProjectionWritePolicy.SaveWithOptimisticConcurrencyAsync.
        //   - Assert: persisted TenantIndexReadModel in Redis contains {tenant-A, tenant-B, tenant-C}.
        //   - Assert: actual save count matches expected (helper-internal observability).
        //   - Cleanup: delete the test state-store key.

        // ACT + ASSERT
        await Task.Yield();
        Should.Throw<NotImplementedException>(() => throw new NotImplementedException(
            "RED PHASE: implement the DAPR-backed conflict-then-success scenario per TODO above."));
    }

    /// <summary>
    /// Probes the local DAPR / Redis state store reachability. Skips the test when
    /// the prerequisite is unavailable (R3-A4 SCP-2026-05-12 pattern). Production-test
    /// parity check; not a substitute for full Aspire Tier 3.
    /// </summary>
    private static void EnsureDaprAvailableOrSkip()
    {
        try
        {
            using var client = new TcpClient();
            IAsyncResult connectResult = client.BeginConnect(DaprStateStoreHost, DaprStateStoreRedisPort, null, null);
            bool connected = connectResult.AsyncWaitHandle.WaitOne(TimeSpan.FromMilliseconds(500));
            if (!connected || !client.Connected)
            {
                Assert.Skip(
                    $"DAPR/Redis state store not reachable at {DaprStateStoreHost}:{DaprStateStoreRedisPort}. " +
                    "Run `dapr init` and ensure the local Redis sidecar is healthy.");
            }
        }
        catch (SocketException ex)
        {
            Assert.Skip(
                $"DAPR/Redis state store probe failed: {ex.SocketErrorCode}. " +
                "Run `dapr init` and ensure the local Redis sidecar is healthy.");
        }
    }
}
