// <copyright file="ProjectionWriteConformanceTests.cs" company="ITANEO">
// Copyright (c) ITANEO. All rights reserved.
// Licensed under the MIT License.
// </copyright>

// ATDD RED-PHASE SCAFFOLDS — generated by /bmad-testarch-atdd 2026-05-19.
// Story: 10.4 (10-4-projection-write-conformance-and-recovery-tests).
// Risk: R-001 (silent last-writer-wins on projection:tenant-index:singleton) — score 9, BLOCK.
// Test design: _bmad-output/test-artifacts/test-design-epic-10.md.
//
// These scaffolds are skipped at the [Fact] level. Story 10.4 dev removes Skip
// after implementing ProjectionWriteConformanceFixture.RunSingletonIndexConformanceAsync
// to invoke the production TenantProjectionWritePolicy directly (R-008 rule).

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Hexalith.EventStore.Contracts.Events;
using Hexalith.EventStore.Contracts.Projections;
using Hexalith.Tenants.Contracts.Events;
using Hexalith.Tenants.Server.Projections;

using Microsoft.Extensions.Logging;

using Shouldly;

namespace Hexalith.Tenants.Server.Tests.Projections;

/// <summary>
/// Tier 1 conformance tests for the singleton tenant-index projection write path.
/// Covers R-001 (silent LWW on projection:tenant-index:singleton).
/// </summary>
public class ProjectionWriteConformanceTests
{
    [Fact(Skip = "ATDD RED PHASE — Story 10.4 must wire ProjectionWriteConformanceFixture.RunSingletonIndexConformanceAsync to invoke TenantProjectionWritePolicy.SaveWithOptimisticConcurrencyAsync<TenantIndexReadModel>. Un-skip once green.")]
    public async Task TenantIndex_ConflictThenSuccess_PreservesAllPreviouslyIndexedTenantsAsync()
    {
        // ARRANGE — R-001 BLOCKER scenario:
        //   Singleton index contains pre-existing tenant-A (attempt 1 reload).
        //   Concurrent write adds tenant-B externally between attempt 1 and attempt 2.
        //   Our incoming event applies tenant-C.
        //   On attempt 1, our save conflicts (ETag mismatch).
        //   On attempt 2, the reload returns the freshly persisted state (with tenant-B),
        //   we apply tenant-C on top, and save succeeds.
        //   Final saved index MUST contain {tenant-A, tenant-B, tenant-C} — zero loss.
        var fixture = new ProjectionWriteConformanceFixture();
        DateTimeOffset timestamp = new(2026, 5, 14, 10, 0, 0, TimeSpan.Zero);

        // Attempt 1: reload sees A only, with stale etag.
        fixture.StateStore.EnqueueRead(
            ProjectionWriteConformanceFixture.TenantIndexProjectionKey,
            ProjectionWriteConformanceFixture.SeedIndexWith(("tenant-a", "Alpha")),
            "index-etag-1");

        // Attempt 2: reload sees A + B (B was added externally), with fresh etag.
        fixture.StateStore.EnqueueRead(
            ProjectionWriteConformanceFixture.TenantIndexProjectionKey,
            ProjectionWriteConformanceFixture.SeedIndexWith(("tenant-a", "Alpha"), ("tenant-b", "Bravo")),
            "index-etag-2");

        fixture.StateStore.EnqueueTrySave(ProjectionWriteConformanceFixture.TenantIndexProjectionKey, false);
        fixture.StateStore.EnqueueTrySave(ProjectionWriteConformanceFixture.TenantIndexProjectionKey, true);

        ProjectionEventDto[] events =
        [
            ProjectionWriteConformanceFixture.CreateEvent(
                new TenantCreated("tenant-c", "Charlie", null, timestamp),
                "evt-c-1",
                timestamp),
        ];

        // ACT — drives production TenantProjectionWritePolicy.SaveWithOptimisticConcurrencyAsync.
        TenantIndexReadModel saved = await fixture.RunSingletonIndexConformanceAsync(events);

        // ASSERT — final state preserves ALL previously indexed tenants + applied incoming.
        saved.ShouldNotBeNull();
        saved.Tenants.Keys.ShouldBe(new[] { "tenant-a", "tenant-b", "tenant-c" }, ignoreOrder: true);
        saved.Tenants["tenant-a"].Name.ShouldBe("Alpha");
        saved.Tenants["tenant-b"].Name.ShouldBe("Bravo");
        saved.Tenants["tenant-c"].Name.ShouldBe("Charlie");

        // Attempt-count invariants (Story 10.4 AC#7).
        fixture.StateStore.ReadCalls
            .Count(c => c.Key == ProjectionWriteConformanceFixture.TenantIndexProjectionKey)
            .ShouldBe(2);
        fixture.StateStore.TrySaveAttempts
            .Count(s => s.Key == ProjectionWriteConformanceFixture.TenantIndexProjectionKey)
            .ShouldBe(2);

        // Per-attempt etag: attempt 1 uses stale etag, attempt 2 uses fresh etag.
        fixture.StateStore.TrySaveAttempts[0].ETag.ShouldBe("index-etag-1");
        fixture.StateStore.TrySaveAttempts[1].ETag.ShouldBe("index-etag-2");

        // Conflict warning emitted (EventId 100101); retry-exhausted NOT emitted.
        fixture.Logger.Entries.ShouldContain(e => e.EventId.Id == 100101 && e.Level == LogLevel.Warning);
        fixture.Logger.Entries.ShouldNotContain(e => e.EventId.Id == 100102);

        // R-008 fixture rule: production policy was invoked, not a test-only reimplementation.
        fixture.BindsToProductionPolicy().ShouldBeTrue();
    }

    [Fact(Skip = "ATDD RED PHASE — Story 10.4 must wire ProjectionWriteConformanceFixture.RunSingletonIndexConformanceAsync. Un-skip once green.")]
    public async Task TenantIndex_RetryExhaustion_FailsObservably_WithoutClaimingSuccessAsync()
    {
        // ARRANGE — 3 consecutive conflicts on the singleton index key.
        //   Production policy budget is MaxAttempts = 3 (TenantProjectionWritePolicy.MaxAttempts).
        //   On exhaustion, the helper throws InvalidOperationException AND emits the
        //   RetryExhausted structured log (EventId 100102, Error). Diagnostic MUST NOT
        //   contain payload bytes, tenant display names, user-controllable labels (R-007).
        var fixture = new ProjectionWriteConformanceFixture();
        DateTimeOffset timestamp = new(2026, 5, 14, 10, 0, 0, TimeSpan.Zero);
        const string SensitiveTenantName = "Confidential Acquisitions Beta Tenant";
        const string SensitiveUserId = "actor-payload-secret-xyz";

        fixture.StateStore.EnqueueRead<TenantIndexReadModel>(
            ProjectionWriteConformanceFixture.TenantIndexProjectionKey,
            null,
            "index-etag-1");
        fixture.StateStore.EnqueueRead<TenantIndexReadModel>(
            ProjectionWriteConformanceFixture.TenantIndexProjectionKey,
            null,
            "index-etag-2");
        fixture.StateStore.EnqueueRead<TenantIndexReadModel>(
            ProjectionWriteConformanceFixture.TenantIndexProjectionKey,
            null,
            "index-etag-3");
        fixture.StateStore.EnqueueTrySave(ProjectionWriteConformanceFixture.TenantIndexProjectionKey, false);
        fixture.StateStore.EnqueueTrySave(ProjectionWriteConformanceFixture.TenantIndexProjectionKey, false);
        fixture.StateStore.EnqueueTrySave(ProjectionWriteConformanceFixture.TenantIndexProjectionKey, false);

        ProjectionEventDto[] events =
        [
            ProjectionWriteConformanceFixture.CreateEvent(
                new TenantCreated("tenant-x", SensitiveTenantName, null, timestamp),
                "evt-sensitive-1",
                timestamp,
                userId: SensitiveUserId),
        ];

        // ACT + ASSERT — exception type, message structure, no false success.
        InvalidOperationException exception = await Should.ThrowAsync<InvalidOperationException>(
            async () => await fixture.RunSingletonIndexConformanceAsync(events));

        exception.Message.ShouldContain("tenant index");
        exception.Message.ShouldContain("3 attempts");

        // Attempt-count invariants (Story 10.4 AC#7): exactly MaxAttempts reads + saves on this key.
        fixture.StateStore.ReadCalls
            .Count(c => c.Key == ProjectionWriteConformanceFixture.TenantIndexProjectionKey)
            .ShouldBe(3);
        fixture.StateStore.TrySaveAttempts
            .Count(s => s.Key == ProjectionWriteConformanceFixture.TenantIndexProjectionKey)
            .ShouldBe(3);

        // Structured-log emission shape (R-016): 2 conflict warnings + 1 retry-exhausted error.
        fixture.Logger.Entries
            .Count(e => e.EventId.Id == 100101 && e.Level == LogLevel.Warning)
            .ShouldBe(2);
        fixture.Logger.Entries
            .Count(e => e.EventId.Id == 100102 && e.Level == LogLevel.Error)
            .ShouldBe(1);

        // R-007 NEGATIVE CONTENT GATE — ZERO TOLERANCE.
        // No log entry (message OR formatted state) may contain sensitive payload content.
        foreach (CapturedLog entry in fixture.Logger.Entries)
        {
            entry.Message.ShouldNotContain(SensitiveTenantName);
            entry.Message.ShouldNotContain(SensitiveUserId);
            entry.StateText.ShouldNotContain(SensitiveTenantName);
            entry.StateText.ShouldNotContain(SensitiveUserId);
        }

        // R-008 fixture rule.
        fixture.BindsToProductionPolicy().ShouldBeTrue();
    }
}
