// <copyright file="ProjectionWriteConformanceFixture.cs" company="ITANEO">
// Copyright (c) ITANEO. All rights reserved.
// Licensed under the MIT License.
// </copyright>

// ATDD RED-PHASE SCAFFOLD — generated by /bmad-testarch-atdd 2026-05-19 for Story 10.4 / risk R-001.
// Test design reference: _bmad-output/test-artifacts/test-design-epic-10.md (T-R001-UNIT-001, T-R001-UNIT-002, T-R001-INT-001).
// R-008 RULE: this fixture MUST drive the production TenantProjectionWritePolicy directly.
// It is forbidden to re-implement retry/merge algorithm logic inside this fixture.

using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;

using Dapr.Client;

using Hexalith.EventStore.Contracts.Events;
using Hexalith.EventStore.Contracts.Projections;
using Hexalith.Tenants.Contracts.Events;
using Hexalith.Tenants.Projections;
using Hexalith.Tenants.Server.Projections;

using Microsoft.Extensions.Logging;

namespace Hexalith.Tenants.Server.Tests.Projections;

/// <summary>
/// Conformance fixture for projection-write safety tests (Story 10.4, R-001 trio).
/// </summary>
/// <remarks>
/// <para>
/// Owns deterministic scripted state-store outcomes, a capturing logger for negative
/// diagnostic-content assertions (risk R-007), and the entry-point method that drives
/// the production <see cref="TenantProjectionWritePolicy"/> helper.
/// </para>
/// <para>
/// R-008 contract: this fixture MUST drive the production helper. It must NEVER
/// re-implement retry / merge / ETag logic in test code. The mechanical assertion
/// in <see cref="BindsToProductionPolicy"/> exists to fail the build if a future
/// refactor tries to substitute a test-only implementation.
/// </para>
/// </remarks>
internal sealed class ProjectionWriteConformanceFixture
{
    public const string StateStoreName = "statestore";
    public const string TenantIndexProjectionKey = "projection:tenant-index:singleton";
    public const string TenantIndexKeyCategory = "tenant index";

    public ScriptedTenantProjectionStateStore StateStore { get; } = new();

    public CapturingLogger<TenantProjectionHandler> Logger { get; } = new();

    /// <summary>
    /// Drives the production singleton-index write path
    /// (<see cref="TenantProjectionWritePolicy.SaveWithOptimisticConcurrencyAsync{TValue}"/>)
    /// against the scripted state store.
    /// </summary>
    /// <remarks>
    /// TODO(Story-10.4): Implement to:
    ///   1. Invoke <see cref="TenantProjectionWritePolicy.SaveWithOptimisticConcurrencyAsync{TValue}"/>
    ///      with <see cref="TenantIndexReadModel"/>, the production <c>ApplyIndexEvent</c> equivalent,
    ///      and the events parameter.
    ///   2. Return the final saved <see cref="TenantIndexReadModel"/> instance so tests can
    ///      assert content.
    ///   3. Keep this method a pass-through — apply NO test-local merge/retry logic.
    /// </remarks>
    public Task<TenantIndexReadModel> RunSingletonIndexConformanceAsync(
        IReadOnlyCollection<ProjectionEventDto?> events) =>
        throw new System.NotImplementedException(
            "ATDD RED PHASE: Story 10.4 must implement ProjectionWriteConformanceFixture." +
            "RunSingletonIndexConformanceAsync by calling TenantProjectionWritePolicy" +
            ".SaveWithOptimisticConcurrencyAsync<TenantIndexReadModel> with the production " +
            "ApplyIndexEvent. Do not re-implement retry/merge logic here (R-008 rule).");

    /// <summary>
    /// Mechanical assertion: confirms this fixture invokes the production helper type
    /// (R-008 rule). A test-only reimplementation MUST fail this assertion.
    /// </summary>
    /// <remarks>
    /// TODO(Story-10.4): Implement by inspecting the call site of the production type
    /// (e.g., via a marker delegate / method reference / type-name assertion). One approach:
    /// store a reference to <see cref="TenantProjectionWritePolicy"/> and assert the
    /// fully-qualified name at fixture construction.
    /// </remarks>
    public bool BindsToProductionPolicy() =>
        throw new System.NotImplementedException(
            "ATDD RED PHASE: Story 10.4 must implement BindsToProductionPolicy to assert " +
            "this fixture drives TenantProjectionWritePolicy (production type), not a " +
            "test-local reimplementation.");

    public static TenantIndexReadModel SeedIndexWith(params (string TenantId, string Name)[] tenants)
    {
        var model = new TenantIndexReadModel();
        foreach ((string tenantId, string name) in tenants)
        {
            model.Apply(new TenantCreated(tenantId, name, null, System.DateTimeOffset.UnixEpoch));
        }

        return model;
    }

    public static ProjectionEventDto CreateEvent(
        IEventPayload payload,
        string messageId,
        System.DateTimeOffset timestamp,
        string correlationId = "corr-1",
        string? userId = "actor-1") =>
        new(
            payload.GetType().FullName!,
            JsonSerializer.SerializeToUtf8Bytes(payload, payload.GetType()),
            "json",
            1,
            timestamp,
            correlationId,
            messageId,
            userId);
}

/// <summary>
/// Scripted, per-key, per-attempt state-store fake for projection-write conformance tests.
/// Mirrors the existing pattern in <c>TenantProjectionHandlerTests</c>; intentionally
/// kept independent so Story 10.4 can extend it without touching the existing handler tests.
/// </summary>
internal sealed class ScriptedTenantProjectionStateStore : ITenantProjectionStateStore
{
    private readonly Dictionary<string, Queue<object>> _reads = [];
    private readonly Dictionary<string, Queue<bool>> _trySaveResults = [];

    public List<ReadCall> ReadCalls { get; } = [];

    public List<SaveAttempt> TrySaveAttempts { get; } = [];

    public List<SaveAttempt> PlainSaveAttempts { get; } = [];

    public void EnqueueRead<TValue>(string key, TValue? value, string? etag)
        where TValue : class
    {
        if (!_reads.TryGetValue(key, out Queue<object>? queue))
        {
            queue = new Queue<object>();
            _reads[key] = queue;
        }

        queue.Enqueue(new ProjectionStateRead<TValue>(value, etag));
    }

    public void EnqueueTrySave(string key, bool result)
    {
        if (!_trySaveResults.TryGetValue(key, out Queue<bool>? queue))
        {
            queue = new Queue<bool>();
            _trySaveResults[key] = queue;
        }

        queue.Enqueue(result);
    }

    public Task<ProjectionStateRead<TValue>> GetStateAndETagAsync<TValue>(
        string storeName,
        string key,
        System.Threading.CancellationToken cancellationToken = default)
        where TValue : class
    {
        ReadCalls.Add(new ReadCall(storeName, key, typeof(TValue)));
        if (!_reads.TryGetValue(key, out Queue<object>? queue) || queue.Count == 0)
        {
            throw new System.InvalidOperationException(
                $"Scripted state store has no remaining read outcomes for key '{key}'. " +
                "Ensure EnqueueRead was called for every expected attempt.");
        }

        return Task.FromResult((ProjectionStateRead<TValue>)queue.Dequeue());
    }

    public Task SaveStateAsync<TValue>(
        string storeName,
        string key,
        TValue value,
        StateOptions? stateOptions = null,
        IReadOnlyDictionary<string, string>? metadata = null,
        System.Threading.CancellationToken cancellationToken = default)
        where TValue : class
    {
        PlainSaveAttempts.Add(new SaveAttempt(
            storeName,
            key,
            value,
            string.Empty,
            stateOptions ?? new StateOptions(),
            typeof(TValue)));
        return Task.CompletedTask;
    }

    public Task<bool> TrySaveStateAsync<TValue>(
        string storeName,
        string key,
        TValue value,
        string etag,
        StateOptions stateOptions,
        IReadOnlyDictionary<string, string>? metadata = null,
        System.Threading.CancellationToken cancellationToken = default)
        where TValue : class
    {
        TrySaveAttempts.Add(new SaveAttempt(storeName, key, value, etag, stateOptions, typeof(TValue)));
        if (!_trySaveResults.TryGetValue(key, out Queue<bool>? queue) || queue.Count == 0)
        {
            throw new System.InvalidOperationException(
                $"Scripted state store has no remaining TrySave outcomes for key '{key}'. " +
                "Ensure EnqueueTrySave was called for every expected attempt.");
        }

        return Task.FromResult(queue.Dequeue());
    }
}

internal sealed record ReadCall(string StoreName, string Key, System.Type ValueType);

internal sealed record SaveAttempt(
    string StoreName,
    string Key,
    object Value,
    string ETag,
    StateOptions StateOptions,
    System.Type ValueType);

/// <summary>
/// Minimal capturing <see cref="ILogger{TCategoryName}"/> for negative-content
/// diagnostic assertions (risk R-007). Records every emitted log entry's level,
/// EventId, formatted message, and state for inspection.
/// </summary>
internal sealed class CapturingLogger<TCategory> : ILogger<TCategory>
{
    public List<CapturedLog> Entries { get; } = [];

    public IDisposable? BeginScope<TState>(TState state)
        where TState : notnull => null;

    public bool IsEnabled(LogLevel logLevel) => true;

    public void Log<TState>(
        LogLevel logLevel,
        EventId eventId,
        TState state,
        System.Exception? exception,
        System.Func<TState, System.Exception?, string> formatter)
    {
        ArgumentNullException.ThrowIfNull(formatter);
        Entries.Add(new CapturedLog(
            logLevel,
            eventId,
            formatter(state, exception),
            state?.ToString() ?? string.Empty,
            exception));
    }
}

internal sealed record CapturedLog(
    LogLevel Level,
    EventId EventId,
    string Message,
    string StateText,
    System.Exception? Exception);
