<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Hexalith.Tenants.AppHost\Hexalith.Tenants.AppHost.csproj" />
    <PackageReference Include="Aspire.Hosting.Testing" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
