<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <NoWarn>$(NoWarn);IDE1006</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\src\Hexalith.Tenants\appsettings.json" CopyToOutputDirectory="PreserveNewest" Link="appsettings.json" />
        <Content Include="..\..\src\Hexalith.Tenants\appsettings.Development.json" CopyToOutputDirectory="PreserveNewest" Link="appsettings.Development.json" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Hexalith.Tenants\Hexalith.Tenants.csproj" />
        <ProjectReference Include="..\..\src\Hexalith.Tenants.Server\Hexalith.Tenants.Server.csproj" />
        <ProjectReference Include="..\..\src\Hexalith.Tenants.Testing\Hexalith.Tenants.Testing.csproj" />
        <ProjectReference Include="..\..\samples\Hexalith.Tenants.Sample\Hexalith.Tenants.Sample.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="YamlDotNet" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
